# Generated by Django 6.0.2 on 2026-03-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_senderaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiprocketorder',
            name='local_status',
            field=models.CharField(choices=[('new_order', 'New Order'), ('order_accepted', 'Order Accepted'), ('order_packed', 'Order Packed'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('order_cancelled', 'Order Cancelled')], default='new_order', max_length=32),
        ),
    ]
