# Generated by Django 6.0.2 on 2026-03-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_shiprocketorder_local_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiprocketorder',
            name='cancellation_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shiprocketorder',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('customer_request', 'Customer Request'), ('payment_failed', 'Payment Failed'), ('out_of_stock', 'Out of Stock'), ('address_issue', 'Address Issue'), ('courier_issue', 'Courier Issue'), ('other', 'Other')], max_length=32),
        ),
        migrations.AddField(
            model_name='shiprocketorder',
            name='label_print_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shiprocketorder',
            name='last_label_printed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
