# Generated by Django 6.0.2 on 2026-03-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_shiprocketorder_cancellation_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiprocketorder',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
