# Generated by Django 6.0.2 on 2026-03-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_shiprocketorder_local_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('api_base_url', models.CharField(blank=True, max_length=255)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Settings',
                'verbose_name_plural': 'WhatsApp Settings',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
