# Generated by Django 6.0.2 on 2026-03-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_whatsappsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappsettings',
            name='test_message_text',
            field=models.CharField(blank=True, default='Hi from Mathukai test message.', max_length=255),
        ),
        migrations.AddField(
            model_name='whatsappsettings',
            name='test_phone_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(blank=True, max_length=128)),
                ('name', models.CharField(max_length=160)),
                ('language', models.CharField(blank=True, max_length=32)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(blank=True, max_length=64)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name', 'language', '-synced_at'],
                'constraints': [models.UniqueConstraint(fields=('name', 'language'), name='uniq_whatsapp_template_name_language')],
            },
        ),
    ]
