# Generated by Django 6.0.2 on 2026-03-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_whatsappsettings_test_message_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappsettings',
            name='test_template_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='whatsappsettings',
            name='test_template_params',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
