# Generated by Django 6.0.2 on 2026-03-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_whatsappsettings_test_template_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppStatusTemplateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_status', models.CharField(max_length=32, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('template_name', models.CharField(blank=True, max_length=160)),
                ('template_id', models.CharField(blank=True, max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Status Template Config',
                'verbose_name_plural': 'WhatsApp Status Template Config',
                'ordering': ['local_status'],
            },
        ),
    ]
