# Generated by Django 6.0.2 on 2026-03-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_whatsappstatustemplateconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappstatustemplateconfig',
            name='template_param_mapping',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
