# Generated by Django 6.0.2 on 2026-03-19 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_whatsappstatustemplateconfig_template_param_mapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shiprocket_order_id', models.CharField(blank=True, max_length=64)),
                ('trigger', models.CharField(choices=[('status_change', 'Status Change'), ('resend', 'Resend'), ('test_message', 'Test Message'), ('test_template', 'Test Template')], default='status_change', max_length=32)),
                ('previous_status', models.CharField(blank=True, max_length=32)),
                ('current_status', models.CharField(blank=True, max_length=32)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('mode', models.CharField(blank=True, max_length=32)),
                ('template_name', models.CharField(blank=True, max_length=160)),
                ('template_id', models.CharField(blank=True, max_length=128)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('is_success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('triggered_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_logs', to='core.shiprocketorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
