# Generated by Django 6.0.2 on 2026-03-19 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_whatsappnotificationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppNotificationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shiprocket_order_id', models.CharField(blank=True, max_length=64)),
                ('trigger', models.CharField(choices=[('status_change', 'Status Change'), ('resend', 'Resend'), ('test_message', 'Test Message'), ('test_template', 'Test Template')], max_length=32)),
                ('previous_status', models.CharField(blank=True, max_length=32)),
                ('current_status', models.CharField(blank=True, max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('retrying', 'Retrying'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('initiated_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_queue_jobs', to='core.shiprocketorder')),
            ],
            options={
                'ordering': ['status', 'next_retry_at', 'created_at'],
            },
        ),
    ]
