# Generated by Django 6.0.2 on 2026-03-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_whatsappnotificationqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappnotificationlog',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='whatsappnotificationqueue',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='whatsappnotificationqueue',
            name='mode',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='whatsappnotificationqueue',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='whatsappnotificationqueue',
            name='template_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='whatsappnotificationqueue',
            name='template_name',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
