# Generated by Django 6.0.2 on 2026-03-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_whatsappnotificationlog_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappnotificationlog',
            name='delivery_status',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='whatsappnotificationlog',
            name='external_message_id',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='whatsappnotificationlog',
            name='webhook_event_id',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='whatsappnotificationlog',
            name='trigger',
            field=models.CharField(choices=[('status_change', 'Status Change'), ('resend', 'Resend'), ('test_message', 'Test Message'), ('test_template', 'Test Template'), ('webhook_status', 'Webhook Status')], default='status_change', max_length=32),
        ),
        migrations.AlterField(
            model_name='whatsappnotificationqueue',
            name='trigger',
            field=models.CharField(choices=[('status_change', 'Status Change'), ('resend', 'Resend'), ('test_message', 'Test Message'), ('test_template', 'Test Template'), ('webhook_status', 'Webhook Status')], max_length=32),
        ),
    ]
