# Generated by Django 6.0.2 on 2026-03-19 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_whatsappnotificationlog_delivery_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shiprocket_order_id', models.CharField(blank=True, max_length=64)),
                ('event_type', models.CharField(choices=[('status_change', 'Status Change'), ('manual_update', 'Manual Update'), ('whatsapp_queued', 'WhatsApp Queued'), ('whatsapp_queue_success', 'WhatsApp Sent'), ('whatsapp_queue_retry', 'WhatsApp Retry'), ('whatsapp_queue_failed', 'WhatsApp Failed'), ('whatsapp_queue_skipped', 'WhatsApp Skipped'), ('whatsapp_webhook', 'WhatsApp Webhook'), ('label_printed', 'Label Printed')], default='status_change', max_length=48)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('previous_status', models.CharField(blank=True, max_length=32)),
                ('current_status', models.CharField(blank=True, max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_success', models.BooleanField(default=True)),
                ('triggered_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='core.shiprocketorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
