# Generated by Django 6.0.2 on 2026-03-22 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_orderactivitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('sku', models.CharField(max_length=120, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'sku'],
            },
        ),
        migrations.AlterField(
            model_name='orderactivitylog',
            name='event_type',
            field=models.CharField(choices=[('status_change', 'Status Change'), ('manual_update', 'Manual Update'), ('whatsapp_queued', 'WhatsApp Queued'), ('whatsapp_queue_success', 'WhatsApp Sent'), ('whatsapp_queue_retry', 'WhatsApp Retry'), ('whatsapp_queue_failed', 'WhatsApp Failed'), ('whatsapp_queue_skipped', 'WhatsApp Skipped'), ('whatsapp_webhook', 'WhatsApp Webhook'), ('label_printed', 'Label Printed'), ('stock_deducted', 'Stock Deducted'), ('stock_restored', 'Stock Restored'), ('stock_warning', 'Stock Warning')], default='status_change', max_length=48),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shiprocket_order_id', models.CharField(blank=True, max_length=64)),
                ('movement_type', models.CharField(choices=[('manual_add', 'Manual Add'), ('manual_remove', 'Manual Remove'), ('manual_set', 'Manual Set'), ('order_accepted', 'Order Accepted Deduction'), ('order_cancelled', 'Order Cancelled Restore')], max_length=32)),
                ('quantity_delta', models.IntegerField()),
                ('quantity_before', models.IntegerField(default=0)),
                ('quantity_after', models.IntegerField(default=0)),
                ('sku_snapshot', models.CharField(blank=True, max_length=120)),
                ('barcode_snapshot', models.CharField(blank=True, max_length=120)),
                ('reference_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('triggered_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='core.shiprocketorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='core.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
