# Generated by Django 6.0.2 on 2026-03-24 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_product_alter_orderactivitylog_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='smartbiz_product_id',
            field=models.CharField(blank=True, max_length=160, null=True, unique=True),
        ),
    ]
