# Generated by Django 6.0.2 on 2026-03-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_product_smartbiz_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
