# Generated by Django 6.0.2 on 2026-03-25 14:27

import django.db.models.deletion
from django.db import migrations, models


def forwards_copy_product_categories(apps, schema_editor):
    Product = apps.get_model("core", "Product")
    ProductCategory = apps.get_model("core", "ProductCategory")

    for product in Product.objects.exclude(category__exact="").iterator():
        category_name = str(product.category or "").strip()
        if not category_name:
            continue
        category_obj, _ = ProductCategory.objects.get_or_create(name=category_name)
        product.category_master_id = category_obj.pk
        product.save(update_fields=["category_master"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.productcategory'),
        ),
        migrations.RunPython(forwards_copy_product_categories, migrations.RunPython.noop),
    ]
