# Generated by Django 6.0.2 on 2026-04-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_productcategory_product_category_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='issue_category',
            field=models.CharField(blank=True, choices=[('free', 'Free'), ('sample', 'Sample'), ('complimentary', 'Complimentary')], max_length=32),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='issue_recipient',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('manual_add', 'Manual Add'), ('manual_remove', 'Manual Remove'), ('manual_set', 'Manual Set'), ('special_issue', 'Free / Sample Issue'), ('order_accepted', 'Order Accepted Deduction'), ('order_cancelled', 'Order Cancelled Restore')], max_length=32),
        ),
    ]
