# Generated by Django 6.0.2 on 2026-04-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_businessexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappnotificationlog',
            name='trigger',
            field=models.CharField(choices=[('status_change', 'Status Change'), ('resend', 'Resend'), ('test_message', 'Test Message'), ('test_template', 'Test Template'), ('webhook_status', 'Webhook Status'), ('webhook_incoming', 'Webhook Incoming')], default='status_change', max_length=32),
        ),
        migrations.AlterField(
            model_name='whatsappnotificationqueue',
            name='trigger',
            field=models.CharField(choices=[('status_change', 'Status Change'), ('resend', 'Resend'), ('test_message', 'Test Message'), ('test_template', 'Test Template'), ('webhook_status', 'Webhook Status'), ('webhook_incoming', 'Webhook Incoming')], max_length=32),
        ),
    ]
