# Generated by Django 6.0.2 on 2026-04-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_whatsappnotificationlog_trigger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappsettings',
            name='account_id',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='whatsappsettings',
            name='account_name',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
