# Generated by Django 6.0.2 on 2026-04-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_expenseperson_businessexpense_expense_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiprocketorder',
            name='packed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
