# Generated by Django 6.0.2 on 2026-05-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_shiprocketorder_packed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiprocketorder',
            name='source',
            field=models.CharField(choices=[('shiprocket', 'Shiprocket'), ('woocommerce', 'WooCommerce')], default='shiprocket', max_length=32),
        ),
        migrations.AddField(
            model_name='shiprocketorder',
            name='woocommerce_order_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='shiprocketorder',
            name='woocommerce_order_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='shiprocketorder',
            name='woocommerce_status',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='shiprocketorder',
            name='woocommerce_status_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiprocketorder',
            name='woocommerce_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
