# Generated by Django 6.0.2 on 2026-05-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_shiprocketorder_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WooCommerceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_url', models.CharField(blank=True, max_length=255)),
                ('consumer_key', models.CharField(blank=True, max_length=255)),
                ('consumer_secret', models.CharField(blank=True, max_length=255)),
                ('import_statuses', models.CharField(blank=True, default='pending,processing,on-hold', max_length=255)),
                ('status_map', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'WooCommerce Settings',
                'verbose_name_plural': 'WooCommerce Settings',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
