# Generated by Django 6.0.2 on 2026-05-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_woocommercesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='woocommercesettings',
            name='webhook_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
