# Generated by Django 6.0.2 on 2026-05-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_webpushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiprocketorder',
            name='courier_name',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
