# Generated by Django 6.0.2 on 2026-06-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_shiprocketorder_courier_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woocommercesettings',
            name='import_statuses',
            field=models.CharField(blank=True, default='pending,processing,on-hold,whatsapp-draft', max_length=255),
        ),
    ]
