# Generated by Django 6.0.2 on 2026-06-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappsettings',
            name='api_key',
            field=models.TextField(blank=True),
        ),
    ]
