# Generated by Django 6.0.2 on 2026-06-26 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


DEFAULT_TENANT_NAME = "Mathukai"
DEFAULT_TENANT_SLUG = "mathukai"


def create_default_tenant_and_memberships(apps, schema_editor):
    Tenant = apps.get_model("core", "Tenant")
    TenantMembership = apps.get_model("core", "TenantMembership")
    Group = apps.get_model("auth", "Group")
    user_app_label, user_model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(user_app_label, user_model_name)

    owner = User.objects.filter(is_active=True, is_superuser=True).order_by("id").first()
    if owner is None:
        owner = User.objects.filter(is_active=True, is_staff=True).order_by("id").first()

    tenant, created = Tenant.objects.get_or_create(
        slug=DEFAULT_TENANT_SLUG,
        defaults={
            "name": DEFAULT_TENANT_NAME,
            "owner": owner,
        },
    )
    if not created and owner and tenant.owner_id is None:
        tenant.owner_id = owner.pk
        tenant.save(update_fields=["owner"])

    ops_viewer_group = Group.objects.filter(name="ops_viewer").first()
    admin_group = Group.objects.filter(name="admin").first()

    for user in User.objects.filter(is_active=True).order_by("id"):
        role = "vendor_owner"
        if ops_viewer_group and user.groups.filter(pk=ops_viewer_group.pk).exists():
            role = "vendor_operator"
        elif admin_group and user.groups.filter(pk=admin_group.pk).exists():
            role = "vendor_owner"

        TenantMembership.objects.get_or_create(
            tenant=tenant,
            user=user,
            defaults={"role": role, "is_active": True},
        )


def remove_default_tenant_memberships(apps, schema_editor):
    Tenant = apps.get_model("core", "Tenant")
    TenantMembership = apps.get_model("core", "TenantMembership")
    tenant = Tenant.objects.filter(slug=DEFAULT_TENANT_SLUG).first()
    if tenant:
        TenantMembership.objects.filter(tenant=tenant).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_product_actual_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contact_name', models.CharField(blank=True, max_length=160)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tenants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('vendor_owner', 'Vendor Owner'), ('vendor_operator', 'Vendor Operator'), ('vendor_viewer', 'Vendor Viewer')], default='vendor_operator', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tenant__name', 'user__username'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'user'), name='uniq_tenant_membership_tenant_user')],
            },
        ),
        migrations.RunPython(create_default_tenant_and_memberships, remove_default_tenant_memberships),
    ]
