# Generated by Django 6.0.2 on 2026-06-26 15:45

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_tenant_tenantmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessexpense',
            name='tenant',
            field=models.ForeignKey(default=core.models.get_default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='business_expenses', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='tenant',
            field=models.ForeignKey(default=core.models.get_default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='contact_messages', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='expenseperson',
            name='tenant',
            field=models.ForeignKey(default=core.models.get_default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='expense_people', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='orderactivitylog',
            name='tenant',
            field=models.ForeignKey(default=core.models.get_default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='order_activity_logs', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='product',
            name='tenant',
            field=models.ForeignKey(default=core.models.get_default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='tenant',
            field=models.ForeignKey(default=core.models.get_default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='project',
            name='tenant',
            field=models.ForeignKey(default=core.models.get_default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='senderaddress',
            name='tenant',
            field=models.ForeignKey(default=core.models.get_default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='sender_addresses', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='shiprocketorder',
            name='tenant',
            field=models.ForeignKey(default=core.models.get_default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='tenant',
            field=models.ForeignKey(default=core.models.get_default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='webpushsubscription',
            name='tenant',
            field=models.ForeignKey(default=core.models.get_default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='web_push_subscriptions', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='whatsappnotificationlog',
            name='tenant',
            field=models.ForeignKey(default=core.models.get_default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_notification_logs', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='whatsappnotificationqueue',
            name='tenant',
            field=models.ForeignKey(default=core.models.get_default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_notification_queue_jobs', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='whatsappsettings',
            name='tenant',
            field=models.ForeignKey(default=core.models.get_default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_settings', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='whatsappstatustemplateconfig',
            name='tenant',
            field=models.ForeignKey(default=core.models.get_default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_status_template_configs', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='whatsapptemplate',
            name='tenant',
            field=models.ForeignKey(default=core.models.get_default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_templates', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='woocommercesettings',
            name='tenant',
            field=models.ForeignKey(default=core.models.get_default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='woocommerce_settings', to='core.tenant'),
        ),
    ]
