# Generated by Django 6.0.2 on 2026-06-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_businessexpense_tenant_contactmessage_tenant_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='whatsapptemplate',
            name='uniq_whatsapp_template_name_language',
        ),
        migrations.AlterField(
            model_name='whatsappstatustemplateconfig',
            name='local_status',
            field=models.CharField(max_length=32),
        ),
        migrations.AddConstraint(
            model_name='whatsappstatustemplateconfig',
            constraint=models.UniqueConstraint(fields=('tenant', 'local_status'), name='uniq_whatsapp_status_config_tenant_status'),
        ),
        migrations.AddConstraint(
            model_name='whatsapptemplate',
            constraint=models.UniqueConstraint(fields=('tenant', 'name', 'language'), name='uniq_whatsapp_template_tenant_name_language'),
        ),
    ]
