# Generated by Django 6.0.2 on 2026-06-26 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_remove_whatsapptemplate_uniq_whatsapp_template_name_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantWooCommerceMappingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('category', 'WooCommerce Category'), ('tag', 'WooCommerce Tag'), ('sku_prefix', 'SKU Prefix'), ('product_id', 'WooCommerce Product ID')], max_length=32)),
                ('match_value', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='woocommerce_mapping_rules', to='core.tenant')),
            ],
            options={
                'ordering': ['tenant__name', 'match_type', 'match_value'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'match_type', 'match_value'), name='uniq_tenant_woocommerce_mapping_rule')],
            },
        ),
    ]
