# Generated by Codex on 2026-06-27

from django.db import migrations, models


def backfill_product_woocommerce_ids(apps, schema_editor):
    Product = apps.get_model("core", "Product")
    for product in Product.objects.all().iterator():
        legacy_id = str(product.smartbiz_product_id or "").strip()
        if not legacy_id:
            continue
        if not product.woocommerce_product_id:
            product.woocommerce_product_id = legacy_id
        product.save(update_fields=["woocommerce_product_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_tenantwoocommercemappingrule"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="woocommerce_product_id",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="product",
            name="woocommerce_variation_id",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.RunPython(backfill_product_woocommerce_ids, migrations.RunPython.noop),
    ]
