# Generated by Django 6.0.2 on 2026-06-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_product_woocommerce_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='WooCommerceSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_type', models.CharField(choices=[('product_sync', 'Product Sync'), ('order_sync', 'Order Sync')], max_length=32)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=16)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('triggered_by', models.CharField(blank=True, max_length=150)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-finished_at', '-started_at'],
            },
        ),
    ]
