# Generated by Django 6.0.2 on 2026-06-28 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_woocommercesyncrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('paid_by', models.CharField(blank=True, max_length=150)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='core.tenant')),
            ],
            options={
                'ordering': ['-period_start', 'tenant__name'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'period_start', 'period_end'), name='unique_vendor_settlement_period')],
            },
        ),
    ]
