# Generated by Django 6.0.2 on 2026-06-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_productchangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='auto_approve_product_changes',
            field=models.BooleanField(default=False),
        ),
    ]
