# Generated by Django 6.0.2 on 2026-07-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_unique_active_whatsapp_queue_idempotency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappnotificationlog',
            name='trigger',
            field=models.CharField(choices=[('status_change', 'Status Change'), ('resend', 'Resend'), ('payment_reminder', 'Payment Reminder'), ('test_message', 'Test Message'), ('test_template', 'Test Template'), ('queue_alert', 'Queue Alert'), ('webhook_status', 'Webhook Status'), ('webhook_incoming', 'Webhook Incoming')], default='status_change', max_length=32),
        ),
        migrations.AlterField(
            model_name='whatsappnotificationqueue',
            name='trigger',
            field=models.CharField(choices=[('status_change', 'Status Change'), ('resend', 'Resend'), ('payment_reminder', 'Payment Reminder'), ('test_message', 'Test Message'), ('test_template', 'Test Template'), ('queue_alert', 'Queue Alert'), ('webhook_status', 'Webhook Status'), ('webhook_incoming', 'Webhook Incoming')], max_length=32),
        ),
    ]
