# Generated by Django 6.0.2 on 2026-07-16 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0062_product_expiry_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="expiry_date",
        ),
    ]
