# Generated by Django 6.0.2 on 2026-07-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_remove_product_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantmembership',
            name='role',
            field=models.CharField(choices=[('vendor_owner', 'Vendor Owner'), ('vendor_operator', 'Vendor Operator'), ('vendor_viewer', 'Vendor Viewer'), ('warehouse_operator', 'Warehouse Operator')], default='vendor_operator', max_length=32),
        ),
    ]
