# Generated by Django 6.0.2 on 2026-07-20 07:49

import core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_mobilesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileRefreshToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=core.models.default_mobile_refresh_expiry)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.mobilerefreshtoken')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='core.mobilesession')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'expires_at'], name='mobile_rt_session_exp_idx'), models.Index(fields=['expires_at', 'revoked_at'], name='mobile_rt_exp_revoke_idx')],
            },
        ),
    ]
