# Generated by Django 6.0.2 on 2026-07-20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0066_mobilerefreshtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="mobilesession",
            name="auth_generation",
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
