# Generated by Django 6.0.2 on 2026-07-20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0067_mobilesession_auth_generation"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiprocketorder",
            name="version",
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
