# Generated by Django 6.0.2 on 2026-07-22 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_shiprocketorder_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileMutationReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed')], default='processing', max_length=16)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutation_receipts', to='core.mobilesession')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_mutation_receipts', to='core.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='mobile_mut_tenant_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('session', 'idempotency_key'), name='uniq_mobile_mutation_session_key')],
            },
        ),
    ]
