# Generated by Django 6.0.2 on 2026-07-22 16:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_mobilemutationreceipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('installation_id', models.UUIDField()),
                ('platform', models.CharField(choices=[('android', 'Android')], default='android', max_length=16)),
                ('expo_push_token', models.CharField(max_length=512, unique=True)),
                ('app_version', models.CharField(max_length=32)),
                ('device_name', models.CharField(blank=True, max_length=120)),
                ('enabled', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_devices', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'enabled'], name='mobdev_tenant_enabled_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'installation_id'), name='uniq_mobile_device_user_install')],
            },
        ),
        migrations.CreateModel(
            name='MobileNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('new_order', 'New Order'), ('order_attention', 'Order Attention'), ('status_change', 'Status Change'), ('routing_alert', 'Routing Alert'), ('integration_alert', 'Integration Alert')], max_length=32)),
                ('title', models.CharField(max_length=160)),
                ('message', models.CharField(max_length=500)),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobile_notifications', to='core.shiprocketorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_notifications', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['tenant', 'user', 'is_read', '-created_at'], name='mobile_notif_inbox_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('order__isnull', False)), fields=('tenant', 'user', 'category', 'order'), name='uniq_mobile_notif_user_order_cat')],
            },
        ),
        migrations.CreateModel(
            name='MobileNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('new_order', 'New Order'), ('order_attention', 'Order Attention'), ('status_change', 'Status Change'), ('routing_alert', 'Routing Alert'), ('integration_alert', 'Integration Alert')], max_length=32)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_notification_preferences', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'user', 'category'), name='uniq_mobile_notif_pref_user_cat')],
            },
        ),
    ]
