"""URL boundary for the version 1 mobile API."""

from django.urls import path

from .views import (
    MobileCurrentSessionView,
    MobileCustomerDetailView,
    MobileCustomerListView,
    MobileCustomerOrderDetailView,
    MobileDashboardView,
    MobileDeviceDetailView,
    MobileExpenseListCreateView,
    MobileExpenseDetailView,
    MobileLoginView,
    MobileLogoutView,
    MobileManualOrderCreateView,
    MobileOrderListView,
    MobileOrderDetailView,
    MobileOrderIssueFlagView,
    MobileOrderPaymentReceivedView,
    MobileOrderShippingAddressView,
    MobileOrderStatusView,
    MobileNotificationListView,
    MobileNotificationPreferencesView,
    MobileNotificationReadView,
    MobilePushTokenView,
    MobileProductListView,
    MobileProductDetailView,
    MobileProductStockView,
    MobileProductSalesReportView,
    MobileStockMovementListView,
    MobileRefreshView,
    MobileSelectTenantView,
    MobileShippingLabelSenderView,
)

app_name = "mobile_api_v1"

urlpatterns = [
    path("auth/login", MobileLoginView.as_view(), name="auth_login"),
    path("auth/refresh", MobileRefreshView.as_view(), name="auth_refresh"),
    path("auth/logout", MobileLogoutView.as_view(), name="auth_logout"),
    path("auth/me", MobileCurrentSessionView.as_view(), name="auth_me"),
    path("auth/select-tenant", MobileSelectTenantView.as_view(), name="auth_select_tenant"),
    path("customers", MobileCustomerListView.as_view(), name="customers"),
    path("customers/<str:customer_key>", MobileCustomerDetailView.as_view(), name="customer_detail"),
    path("customers/<str:customer_key>/orders/<int:order_id>", MobileCustomerOrderDetailView.as_view(), name="customer_order_detail"),
    path("dashboard", MobileDashboardView.as_view(), name="dashboard"),
    path("reports/product-sales", MobileProductSalesReportView.as_view(), name="product_sales_report"),
    path("expenses", MobileExpenseListCreateView.as_view(), name="expenses"),
    path("expenses/<int:expense_id>", MobileExpenseDetailView.as_view(), name="expense_detail"),
    path("manual-orders", MobileManualOrderCreateView.as_view(), name="manual_orders"),
    path("shipping-label/sender", MobileShippingLabelSenderView.as_view(), name="shipping_label_sender"),
    path("orders", MobileOrderListView.as_view(), name="orders"),
    path("orders/<int:order_id>", MobileOrderDetailView.as_view(), name="order_detail"),
    path("orders/<int:order_id>/issue", MobileOrderIssueFlagView.as_view(), name="order_issue"),
    path("orders/<int:order_id>/status", MobileOrderStatusView.as_view(), name="order_status"),
    path(
        "orders/<int:order_id>/payment-received",
        MobileOrderPaymentReceivedView.as_view(),
        name="order_payment_received",
    ),
    path(
        "orders/<int:order_id>/shipping-address",
        MobileOrderShippingAddressView.as_view(),
        name="order_shipping_address",
    ),
    path("products", MobileProductListView.as_view(), name="products"),
    path("products/<int:product_id>", MobileProductDetailView.as_view(), name="product_detail"),
    path("products/<int:product_id>/stock", MobileProductStockView.as_view(), name="product_stock"),
    path("stock/movements", MobileStockMovementListView.as_view(), name="stock_movements"),
    path("notifications", MobileNotificationListView.as_view(), name="notifications"),
    path(
        "notifications/<int:notification_id>/read",
        MobileNotificationReadView.as_view(),
        name="notification_read",
    ),
    path(
        "notification-preferences",
        MobileNotificationPreferencesView.as_view(),
        name="notification_preferences",
    ),
    path("devices/push-token", MobilePushTokenView.as_view(), name="device_push_token"),
    path("devices/<uuid:device_id>", MobileDeviceDetailView.as_view(), name="device_detail"),
]
