from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .forms import LoginForm
from .views import (
    bulk_shipping_labels_4x6,
    bulk_packing_lists,
    audit_export_csv,
    admin_utilities,
    contact,
    expense_tracker,
    healthz,
    home,
    metrics,
    order_management_export_csv,
    order_management,
    order_management_delete_view,
    order_management_save_view,
    order_management_undo_last_action,
    order_detail,
    order_notification_config,
    ops_bulk_shipping_labels_4x6,
    ops_bulk_shipping_labels_pdf,
    ops_print_queue,
    packing_queue,
    packing_list,
    print_queue,
    process_whatsapp_queue_now,
    project_detail,
    project_list,
    product_categories,
    manifest_webmanifest,
    offline_page,
    run_integration_smoke,
    run_restore_dry_run,
    retry_failed_whatsapp_queue,
    resend_shiprocket_order_whatsapp,
    bulk_resend_shiprocket_order_whatsapp,
    bulk_update_shiprocket_order_status,
    sender_address,
    shipping_label_4x6,
    shipping_label_test_4x6,
    signup,
    special_stock_issue_register,
    stock_management,
    sync_shiprocket_orders,
    track_bulk_shipping_labels_print,
    track_shipping_label_print,
    whatomate_webhook,
    whatsapp_delivery_logs,
    whatsapp_delivery_logs_csv,
    service_worker,
    webhook_diagnostics,
    whatsapp_settings,
    update_shiprocket_order,
    update_shiprocket_order_status,
)

urlpatterns = [
    path("manifest.webmanifest", manifest_webmanifest, name="pwa_manifest"),
    path("service-worker.js", service_worker, name="service_worker"),
    path("offline/", offline_page, name="offline_page"),
    path('', home, name='home'),
    path("orders/management/", order_management, name="order_management"),
    path("orders/management/views/save/", order_management_save_view, name="order_management_save_view"),
    path("orders/management/views/delete/", order_management_delete_view, name="order_management_delete_view"),
    path("orders/management/undo/", order_management_undo_last_action, name="order_management_undo_last_action"),
    path("orders/management/export.csv", order_management_export_csv, name="order_management_export_csv"),
    path("healthz/", healthz, name="healthz"),
    path("metrics/", metrics, name="metrics"),
    path("orders/<int:pk>/", order_detail, name="order_detail"),
    path("orders/<int:pk>/packing-list/", packing_list, name="packing_list"),
    path("orders/packing-queue/", packing_queue, name="packing_queue"),
    path("orders/packing-list/bulk/", bulk_packing_lists, name="bulk_packing_lists"),
    path("orders/ops/print-queue/", ops_print_queue, name="ops_print_queue"),
    path("orders/ops/labels-4x6/bulk/", ops_bulk_shipping_labels_4x6, name="ops_bulk_shipping_labels_4x6"),
    path("orders/ops/labels-4x6/pdf/", ops_bulk_shipping_labels_pdf, name="ops_bulk_shipping_labels_pdf"),
    path("orders/label-4x6/test/", shipping_label_test_4x6, name="shipping_label_test_4x6"),
    path("orders/<int:pk>/label-4x6/", shipping_label_4x6, name="shipping_label_4x6"),
    path("orders/<int:pk>/label-4x6/track-print/", track_shipping_label_print, name="track_shipping_label_print"),
    path("orders/print-queue/", print_queue, name="print_queue"),
    path("orders/labels-4x6/bulk/", bulk_shipping_labels_4x6, name="bulk_shipping_labels_4x6"),
    path(
        "orders/labels-4x6/bulk/track-print/",
        track_bulk_shipping_labels_print,
        name="track_bulk_shipping_labels_print",
    ),
    path("orders/<int:pk>/update/", update_shiprocket_order, name="update_shiprocket_order"),
    path("orders/<int:pk>/status/", update_shiprocket_order_status, name="update_shiprocket_order_status"),
    path("orders/bulk/status/", bulk_update_shiprocket_order_status, name="bulk_update_shiprocket_order_status"),
    path("orders/bulk/resend-whatsapp/", bulk_resend_shiprocket_order_whatsapp, name="bulk_resend_shiprocket_order_whatsapp"),
    path("orders/<int:pk>/resend-whatsapp/", resend_shiprocket_order_whatsapp, name="resend_shiprocket_order_whatsapp"),
    path("whatsapp-queue/retry-failed/", retry_failed_whatsapp_queue, name="retry_failed_whatsapp_queue"),
    path("whatsapp-queue/process-now/", process_whatsapp_queue_now, name="process_whatsapp_queue_now"),
    path("integration-smoke/run/", run_integration_smoke, name="run_integration_smoke"),
    path("restore/dry-run/", run_restore_dry_run, name="run_restore_dry_run"),
    path("audit-export.csv", audit_export_csv, name="audit_export_csv"),
    path("sender-address/", sender_address, name="sender_address"),
    path("expenses/", expense_tracker, name="expense_tracker"),
    path("stock-management/", stock_management, name="stock_management"),
    path("stock-issues/", special_stock_issue_register, name="special_stock_issue_register"),
    path("product-categories/", product_categories, name="product_categories"),
    path("whatsapp-settings/", whatsapp_settings, name="whatsapp_settings"),
    path("webhook-diagnostics/", webhook_diagnostics, name="webhook_diagnostics"),
    path("webhooks/whatomate/", whatomate_webhook, name="whatomate_webhook"),
    path("whatsapp-delivery-logs/", whatsapp_delivery_logs, name="whatsapp_delivery_logs"),
    path("whatsapp-delivery-logs/export.csv", whatsapp_delivery_logs_csv, name="whatsapp_delivery_logs_csv"),
    path("admin-utilities/", admin_utilities, name="admin_utilities"),
    path("order-notification-config/", order_notification_config, name="order_notification_config"),
    path("projects/", project_list, name="project_list"),
    path("projects/<int:pk>/", project_detail, name="project_detail"),
    path("contact/", contact, name="contact"),
    path("shiprocket/sync/", sync_shiprocket_orders, name="sync_shiprocket_orders"),
    path(
        "accounts/login/",
        LoginView.as_view(
            template_name="registration/login.html",
            authentication_form=LoginForm,
        ),
        name="login",
    ),
    path("accounts/logout/", LogoutView.as_view(), name="logout"),
    path("accounts/signup/", signup, name="signup"),
]
