"""
Django settings for Ram_codex1 project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_local_env():
    env_path = BASE_DIR / ".env"
    if not env_path.exists():
        return
    try:
        for raw_line in env_path.read_text(encoding="utf-8").splitlines():
            line = raw_line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            key = key.strip()
            value = value.strip()
            if not key:
                continue
            if (
                len(value) >= 2
                and ((value[0] == '"' and value[-1] == '"') or (value[0] == "'" and value[-1] == "'"))
            ):
                value = value[1:-1]
            os.environ.setdefault(key, value)
    except OSError:
        # Keep startup resilient even if .env can't be read.
        return


_load_local_env()


def _env_bool(name, default=False):
    raw_value = os.environ.get(name)
    if raw_value is None:
        return bool(default)
    return str(raw_value).strip().lower() in {'1', 'true', 'yes', 'on'}


def _env_csv(name, default_value=''):
    raw_value = os.environ.get(name, default_value)
    return [item.strip() for item in str(raw_value or '').split(',') if item.strip()]


def _database_config():
    database_url = os.environ.get("DATABASE_URL", "").strip()
    if database_url:
        parsed = urlparse(database_url)
        scheme = parsed.scheme.lower()
        if scheme == "sqlite":
            db_path = unquote(parsed.path or "").strip() or "/app/db.sqlite3"
            if db_path.startswith("/"):
                db_path = Path(db_path)
            else:
                db_path = BASE_DIR / db_path
            return {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": db_path,
            }
        if scheme in {"postgres", "postgresql", "pgsql"}:
            query = parse_qs(parsed.query)
            options = {}
            ssl_mode = query.get("sslmode", [os.environ.get("POSTGRES_SSLMODE", "")])[0]
            if ssl_mode:
                options["sslmode"] = ssl_mode
            return {
                "ENGINE": "django.db.backends.postgresql",
                "NAME": unquote(parsed.path.lstrip("/") or os.environ.get("POSTGRES_DB", "")),
                "USER": unquote(parsed.username or os.environ.get("POSTGRES_USER", "")),
                "PASSWORD": unquote(parsed.password or os.environ.get("POSTGRES_PASSWORD", "")),
                "HOST": parsed.hostname or os.environ.get("POSTGRES_HOST", "localhost"),
                "PORT": parsed.port or os.environ.get("POSTGRES_PORT", "5432"),
                "CONN_MAX_AGE": int(os.environ.get("POSTGRES_CONN_MAX_AGE", "60") or 60),
                "OPTIONS": options,
            }
        raise ValueError(f"Unsupported DATABASE_URL scheme: {scheme}")

    if os.environ.get("POSTGRES_DB"):
        options = {}
        ssl_mode = os.environ.get("POSTGRES_SSLMODE", "").strip()
        if ssl_mode:
            options["sslmode"] = ssl_mode
        return {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("POSTGRES_DB", ""),
            "USER": os.environ.get("POSTGRES_USER", ""),
            "PASSWORD": os.environ.get("POSTGRES_PASSWORD", ""),
            "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
            "PORT": os.environ.get("POSTGRES_PORT", "5432"),
            "CONN_MAX_AGE": int(os.environ.get("POSTGRES_CONN_MAX_AGE", "60") or 60),
            "OPTIONS": options,
        }

    return {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-g89cihbcu*2#mcv$-ahlpl#9*sp(%0l2hc^l&bdkzwu@3ssa%x",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DJANGO_DEBUG', True)

ALLOWED_HOSTS = _env_csv('DJANGO_ALLOWED_HOSTS', '')
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'testserver','192.168.1.5']

CSRF_TRUSTED_ORIGINS = _env_csv('DJANGO_CSRF_TRUSTED_ORIGINS', '')
SESSION_COOKIE_SECURE = _env_bool('DJANGO_SESSION_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_SECURE = _env_bool('DJANGO_CSRF_COOKIE_SECURE', not DEBUG)
SECURE_SSL_REDIRECT = _env_bool('DJANGO_SECURE_SSL_REDIRECT', False)
if _env_bool('DJANGO_USE_X_FORWARDED_PROTO', False):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Ram_codex1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.role_flags',
            ],
        },
    },
]

WSGI_APPLICATION = 'Ram_codex1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': _database_config()
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"

SHIPROCKET_BASE_URL = os.environ.get("SHIPROCKET_BASE_URL", "https://apiv2.shiprocket.in/v1/external")
SHIPROCKET_EMAIL = os.environ.get("SHIPROCKET_EMAIL", "")
SHIPROCKET_PASSWORD = os.environ.get("SHIPROCKET_PASSWORD", "")

WHATOMATE_ENABLED = os.environ.get("WHATOMATE_ENABLED", "false")
WHATOMATE_BASE_URL = os.environ.get("WHATOMATE_BASE_URL", "http://127.0.0.1:8080")
WHATOMATE_API_KEY = os.environ.get("WHATOMATE_API_KEY", "")
WHATOMATE_ACCESS_TOKEN = os.environ.get("WHATOMATE_ACCESS_TOKEN", "")
WHATOMATE_DEFAULT_COUNTRY_CODE = os.environ.get("WHATOMATE_DEFAULT_COUNTRY_CODE", "91")
WHATOMATE_ACCOUNT_ID = os.environ.get("WHATOMATE_ACCOUNT_ID", "")
WHATOMATE_ACCOUNT_NAME = os.environ.get("WHATOMATE_ACCOUNT_NAME", "")
WHATOMATE_WEBHOOK_TOKEN = os.environ.get("WHATOMATE_WEBHOOK_TOKEN", "")
WHATOMATE_ORDER_ACCEPTED_USE_TEMPLATE = os.environ.get("WHATOMATE_ORDER_ACCEPTED_USE_TEMPLATE", "false")
WHATOMATE_ORDER_ACCEPTED_TEMPLATE_NAME = os.environ.get("WHATOMATE_ORDER_ACCEPTED_TEMPLATE_NAME", "")
WHATOMATE_ORDER_ACCEPTED_TEXT = os.environ.get(
    "WHATOMATE_ORDER_ACCEPTED_TEXT",
    "Hi {customer_name}, your order {order_id} has been accepted. We will share the next update soon.",
)

WHATSAPP_ALERTS_ENABLED = os.environ.get("WHATSAPP_ALERTS_ENABLED", "true")
WHATSAPP_ALERT_FAILED_THRESHOLD = int(os.environ.get("WHATSAPP_ALERT_FAILED_THRESHOLD", "10") or 10)
WHATSAPP_ALERT_COOLDOWN_MINUTES = int(os.environ.get("WHATSAPP_ALERT_COOLDOWN_MINUTES", "30") or 30)
WHATSAPP_ALERT_EMAIL_TO = os.environ.get("WHATSAPP_ALERT_EMAIL_TO", "")
WHATSAPP_ALERT_WHATSAPP_TO = os.environ.get("WHATSAPP_ALERT_WHATSAPP_TO", "")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "noreply@localhost")
RUNTIME_HEARTBEAT_RETENTION_DAYS = int(os.environ.get("RUNTIME_HEARTBEAT_RETENTION_DAYS", "30") or 30)
RUNTIME_LOG_RETENTION_DAYS = int(os.environ.get("RUNTIME_LOG_RETENTION_DAYS", "30") or 30)
LOGIN_LOCKOUT_ATTEMPTS = int(os.environ.get("LOGIN_LOCKOUT_ATTEMPTS", "5") or 5)
LOGIN_LOCKOUT_WINDOW_SECONDS = int(os.environ.get("LOGIN_LOCKOUT_WINDOW_SECONDS", "900") or 900)
LOGIN_LOCKOUT_DURATION_SECONDS = int(os.environ.get("LOGIN_LOCKOUT_DURATION_SECONDS", "900") or 900)
WEBHOOK_STALE_MINUTES = int(os.environ.get("WEBHOOK_STALE_MINUTES", "30") or 30)
METRICS_TOKEN = os.environ.get("METRICS_TOKEN", "")

LOG_DIR = BASE_DIR / "logs"
try:
    LOG_DIR.mkdir(parents=True, exist_ok=True)
except OSError:
    pass

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "%(asctime)s | %(levelname)s | %(name)s | %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
        "app_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_DIR / "app.log"),
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 5,
            "formatter": "standard",
            "encoding": "utf-8",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "app_file"],
            "level": "INFO",
            "propagate": True,
        },
        "core": {
            "handlers": ["console", "app_file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
